name: flutterpersistentnavbar
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  persistent_bottom_nav_bar: ^1.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Light.ttf
          weight: 400
        - asset: assets/fonts/Vazir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 700
